source "https://rubygems.org"
ruby "2.3.0"

gem "bower"
gem "devise"
gem "figaro"
gem "font-awesome-sass"
gem "formtastic"
gem "gibbon"
gem "gon"
gem "haml-rails"
gem "jquery-rails"
gem "kaminari"
gem "mysql2"
gem "newrelic_rpm"
gem "puma"
gem "rails"
gem "rails_12factor", group: :production
gem "sass-rails"
gem "sucker_punch"
gem "transloadit-rails"
gem "turbolinks"
gem "uglifier"

group :development, :test do
  gem "awesome_print"
  gem "byebug"
  gem "faker"
  gem "pry"
  gem "quiet_assets"
  gem "spring"
  gem "web-console"
end
